import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { AppProvider } from '@/context/AppContext';

const k2dFont = K2D({
  subsets: ["latin"], // Asegúrate de especificar los subsets
  weight: ["400", "700"], // Puedes ajustar los pesos que necesites
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2dFont.className} antialiased relative`}>
        <AppProvider>
          <Header />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
